// ══════════════════════════════════════════════════
// modal.js — AI Content modal logic
// Depends on: utils.js (showToast)
// ══════════════════════════════════════════════════

let currentAIContent = null;

/** Open modal using cached video index */
function openModalByIndex(index) {
  const video = cachedVideos[index];
  if (!video) return;
  openModal(video.title, video.ai_content);
}

/** Open the AI study content modal */
function openModal(title, aiContent) {
  currentAIContent = aiContent;

  const modalOverlay = document.getElementById('modal-overlay');
  const modalContent = document.getElementById('modal-content');
  const modalTitle   = document.getElementById('modal-title');

  modalTitle.textContent = title;

  // Populate tabs
  document.getElementById('tab-summary').innerHTML = `
    <p class="text-slate-300 leading-relaxed text-[15px]">${aiContent.summary}</p>`;

  document.getElementById('tab-concepts').innerHTML = `
    <div class="flex flex-wrap gap-2">
      ${aiContent.key_concepts.map(c => `<span class="px-3 py-1.5 rounded-full bg-brand-600/15 border border-brand-500/20 text-brand-300 text-sm font-medium">${c}</span>`).join('')}
    </div>`;

  document.getElementById('tab-explanation').innerHTML = `
    <p class="text-slate-300 leading-relaxed text-[15px] whitespace-pre-line">${aiContent.explanation_for_students}</p>`;

  document.getElementById('tab-quiz').innerHTML = `
    <ol class="space-y-3 list-decimal list-inside">
      ${aiContent.quiz_questions.map(q => `<li class="text-slate-300 text-[15px] leading-relaxed">${q}</li>`).join('')}
    </ol>`;

  // Reset to first tab
  activateTab('summary');

  // Show modal
  modalOverlay.classList.remove('hidden');
  document.body.style.overflow = 'hidden';
  requestAnimationFrame(() => {
    modalContent.classList.remove('opacity-0', 'translate-y-10');
    modalContent.classList.add('opacity-100', 'translate-y-0');
  });
}

/** Close the modal */
function closeModal() {
  const modalOverlay = document.getElementById('modal-overlay');
  const modalContent = document.getElementById('modal-content');

  modalContent.classList.remove('opacity-100', 'translate-y-0');
  modalContent.classList.add('opacity-0', 'translate-y-10');
  setTimeout(() => {
    modalOverlay.classList.add('hidden');
    document.body.style.overflow = '';
  }, 300);
}

/** Switch active tab */
function activateTab(tabName) {
  document.querySelectorAll('.modal-tab').forEach(t => {
    t.classList.remove('tab-active');
    t.classList.add('text-slate-500');
  });
  document.querySelectorAll('.tab-content').forEach(c => c.classList.add('hidden'));

  const activeTab = document.querySelector(`.modal-tab[data-tab="${tabName}"]`);
  if (activeTab) {
    activeTab.classList.add('tab-active');
    activeTab.classList.remove('text-slate-500');
  }
  const activeContent = document.getElementById(`tab-${tabName}`);
  if (activeContent) activeContent.classList.remove('hidden');
}

/** Build plain-text notes for clipboard */
function buildNotesText() {
  if (!currentAIContent) return '';
  const title = document.getElementById('modal-title').textContent;
  return [
    `📚 AI Study Notes — ${title}`,
    `${'─'.repeat(50)}`,
    ``,
    `📝 SUMMARY`,
    currentAIContent.summary,
    ``,
    `🔑 KEY CONCEPTS`,
    currentAIContent.key_concepts.map(c => `  • ${c}`).join('\n'),
    ``,
    `💡 SIMPLE EXPLANATION`,
    currentAIContent.explanation_for_students,
    ``,
    `❓ QUIZ QUESTIONS`,
    currentAIContent.quiz_questions.map((q, i) => `  ${i + 1}. ${q}`).join('\n'),
    ``,
    `— Generated by EduTube AI`
  ].join('\n');
}
